### ISSUE TITLE
Allow requesting all contact keys

### ISSUE THREAD

**Issue by KishanBagaria** [codebytere/node-mac-contacts#5]
Might be worth making all the keys available that are listed here: https://developer.apple.com/documentation/contacts/contact_keys

I've forked it locally to get a few string keys for my use case.

The get functions can take in an additional param, an array of requested keys, which can default to the keys it currently returns.

**Comment by codebytere** [comment]
I'm happy to take this one on, but i'll need a bit to think about exactly how i want to add this without exposing too many Objective-C implementation details. It's not great dx to pass in raw strings like they're [found here](https://developer.apple.com/documentation/contacts/contact_keys?language=objc).

Two possible approaches:

1) Expand the defaults, and add an extra optional options object parameter which returns a contact containing only those values which were passed (in altered format, e.g passing 'jobTitle' for `CNContactJobTitleKey` would return a bunch of objects only containing `jobTitle`s)

2) Leave the defaults as they are, and and add an extra optional parameter which adds all keys passed to it to the existing defaults (e.g passing `jobTitle` would return `jobTitle` in addition to the previously returned values).

I personally prefer #2, so that's what i'll proceed with unless you feel differently!

**Comment by KishanBagaria** [comment]
Sounds good. 

Just wondering about the performance here. Some people have 1000s of contacts and if the contact image buffer is returned for all, it might take a while. How about if you add an optional keys array param that if null, returns the default keys (the ones that it does now)? This will allow people to request only the keys that they require.

**Comment by codebytere** [comment]
That was my other concern - i think i might move the contact picture to optional params and only return it if requested as part of the optional extra keys.

I also probably won't add _every_ available key since there are loads and some of them are super specific and not of use to most people; would you mind letting me know of any that are important to you so i can make sure to add them?

**Comment by KishanBagaria** [comment]
Was in the middle of typing this then saw the PR.

---

Good idea.

I was just trying to render the whole contact pane exactly like Contacts.app but there's a few keys that I won't require. Can I update your PR with support for some more keys?

**Comment by codebytere** [comment]
@KishanBagaria it'll likely be faster if you wouldn't mind just listing the keys you need on the PR!

**Comment by KishanBagaria** [comment]
I need all the social profiles / IM handles, URLs, the thumbnail image and the job organization name.

Thanks for your work on this!

**Comment by codebytere** [comment]
Can do! Should be done within a few hours.

**Comment by KishanBagaria** [comment]
Btw I implemented the thumbnail image here: https://github.com/KishanBagaria/node-mac-contacts/blob/add-optional-keys/contacts.mm

You might be able to copy some lines.

**Comment by codebytere** [comment]
Closed in 6d844e0.

I need to add some extra error handling to catch incorrectly spelled `extraProperties` and whatnot but all new keys are now in `master` and i'll publish when that's been done.

**Comment by codebytere** [comment]
@KishanBagaria [`v1.1.0`](https://github.com/codebytere/node-mac-contacts/releases/tag/v1.1.0) published with all new properties.

**Comment by KishanBagaria** [comment]
Thank you so much!
